string = input("Digite alguma coisa:")

print(f"O tipo primitivo desse valor é {type(string)}")
print(f'Só tem espaços? {string.isspace()}')
print(f"É um número? {string.isnumeric()}")
print(f"É alfabético? {string.isalpha()}")
print(f"É alfanúmerico? {string.isalnum()}")
print(f"Está em maiúsculas? {string.isupper()}")
print(f"Está em minúsculas? {string.islower()}")
print(f"Está capitalizado? {string.istitle()}")